// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/greeter.proto

package com.niyongcheng.examples.greeter;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
